const axios = require("axios");
const { parseStructuredReview } = require("../utils/reviewParser.util");
const { getCodeQualityScore } = require("../utils/score.util");

const HF_MODEL = process.env.HF_MODEL || "Qwen/Qwen2.5-Coder-32B-Instruct";
const HF_URL = "https://router.huggingface.co/v1/chat/completions";

const normalizeDiffReview = (text) => {
  try {
    const parsed = JSON.parse(text);
    if (parsed && typeof parsed === "object") {
      return {
        changesSummary: typeof parsed.changesSummary === "string" ? parsed.changesSummary : "",
        issuesInChanges: Array.isArray(parsed.issuesInChanges) ? parsed.issuesInChanges : [],
        improvements: Array.isArray(parsed.improvements) ? parsed.improvements : [],
      };
    }
  } catch (_) {
    // Fallback text parsing
  }

  const lines = text
    .split(/\n|;\s+/)
    .map((line) => line.replace(/^[-*]\s*/, "").trim())
    .filter(Boolean);
  const issuesInChanges = lines.filter((line) => /(bug|issue|error|risk|vulnerab)/i.test(line));
  const improvements = lines.filter((line) => /(improve|refactor|optimi|clean|suggest)/i.test(line));
  const changesSummary = lines.slice(0, 2).join(" ");

  return {
    changesSummary: changesSummary || "Changes detected and reviewed.",
    issuesInChanges,
    improvements,
  };
};

const getAIResponse = async ({ code, previousCode, mode = "developer", compareChanges = false }) => {
  if (!process.env.HF_TOKEN) {
    throw new Error("HF_TOKEN is missing in environment variables.");
  }

  const isBeginner = mode === "beginner";
  const systemInstruction = isBeginner
    ? "You are a friendly coding mentor. Explain in very simple language, avoid jargon, and use analogies when useful."
    : "You are a senior code reviewer.";

  const prompt = compareChanges && previousCode
    ? [
        "Compare the previous code and updated code.",
        "Focus ONLY on differences.",
        "Explain added, removed, and modified logic.",
        "Return valid JSON with keys:",
        "{",
        '  "changesSummary": "short summary",',
        '  "issuesInChanges": ["..."],',
        '  "improvements": ["..."]',
        "}",
        isBeginner
          ? "Keep explanations beginner-friendly and avoid technical jargon."
          : "Use technical, precise review language.",
        "",
        "PREVIOUS CODE:",
        previousCode,
        "",
        "UPDATED CODE:",
        code,
      ].join("\n")
    : [
        "Review this code and provide:",
        "1) bugs",
        "2) security issues",
        "3) performance improvements",
        "4) readability suggestions",
        isBeginner
          ? "Explain issues in simple words and use real-world analogies if possible."
          : "Use technical developer-level explanations.",
        "",
        code,
      ].join("\n");

  try {
    const response = await axios.post(
      HF_URL,
      {
        model: HF_MODEL,
        messages: [
          {
            role: "system",
            content: systemInstruction,
          },
          {
            role: "user",
            content: prompt,
          },
        ],
        max_tokens: 500,
        temperature: 0.2,
      },
      {
        headers: {
          Authorization: `Bearer ${process.env.HF_TOKEN}`,
          "Content-Type": "application/json",
        },
        timeout: 60000,
      }
    );

    const data = response.data;
    const reviewText = data?.choices?.[0]?.message?.content?.trim() || "No review generated by model.";
    const structuredReview =
      compareChanges && previousCode
        ? normalizeDiffReview(reviewText)
        : parseStructuredReview(reviewText);
    const score = getCodeQualityScore({ code, aiResponse: reviewText });

    return {
      rawReview: reviewText,
      structuredReview: structuredReview || reviewText,
      score,
      mode,
      compareChanges,
    };
  } catch (error) {
    const hfError = error.response?.data?.error || error.response?.data || error.message;
    console.error("Hugging Face API error:", hfError);
    throw new Error(typeof hfError === "string" ? hfError : JSON.stringify(hfError));
  }
};

module.exports = getAIResponse;